---
ENABLE_LINTERS:
  - JAVASCRIPT_PRETTIER
  - JAVASCRIPT_ES
  - PHP_PHPCS
  - PHP_PHPSTAN
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - SPELL_CSPELL

FORMATTERS_DISABLE_ERRORS: false
 
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
YAML_PRETTIER_CONFIG_FILE: .prettierrc.yml
PHP_PHPCS_CONFIG_FILE: .php_cs
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettierrc.yml
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
