# The default styles that are applied to every file prettied with prettier

embeddedLanguageFormatting: auto
endOfLine: lf
trailingComma: es5
useTabs: false
printWidth: 120
insertPragma: false
requirePragma: false
bracketSpacing: true
tabWidth: 2
singleQuote: false
semi: true
proseWrap: always

# Overrides the default for certain files extensions

overrides:
  - files: "*.vue"
    options:
      tabWidth: 4
      singleQuote: true
      arrowParens: always
      proseWrap: never
      
  - files: "*.js"
    options:
      tabWidth: 4
      singleQuote: true
      arrowParens: always
      proseWrap: never

  - files: "*.{scss,css}"
    options:
      tabWidth: 4

  - files: "*.ts"
    options:
      tabWidth: 4
      singleQuote: true
      arrowParens: always
      proseWrap: never

  - files: "*.json"
    options:
      singleQuote: true
      tabWidth: 4

  - files: "*.php"
    options:
      tabWidth: 4
      singleQuote: true
